### ISSUE TITLE
#project line mandatory

### ISSUE THREAD

**Issue by EleanorRobson** [oracc/oraccdoc#1]
In http://oracc.museum.upenn.edu/doc/help/editinginatf/primer/index.html it still implies that the #project line is nice but entirely optional, though it has been mandatory for years. 

Also needs to say that the #project line must come before the #atf protocol lines.

**Comment by jnovotny-lmu** [comment]
@EleanorRobson 
I have changed the doc to read:
"It is mandatory that you specify the project that the text belongs too; this is particularly useful if the project uses a standard set of protocols and conventions. In addition, the #project line must come before the #atf protocol lines." I have also changed the data in the examples to have the #project line above the #atf lines. If ratified with the change, we can close this.

**Comment by EleanorRobson** [comment]
Thanks! A couple of small tweaks: "belongs to" not "too" and replace, "this is particularly useful if the project uses a standard set of protocols and conventions." with " The ATF file is not valid if this line is omitted, as it sends essential information to the server, used for validation and lemmatisation."

**Comment by jnovotny-lmu** [comment]
Thanks! Done. The "too" was in the original file, as I did not change that part of the sentence.
